[package]
name = "agri-stream"
version = "0.1.0"
edition = "2021"
description = "Soroban smart contract for immediate, transparent USDC disaster aid allocation to Filipino farmers."
license = "MIT"
repository = "https://github.com/jemslzr/AgriStream"
homepage = "https://agri-stream-zkd6.vercel.app/"
keywords = ["soroban", "stellar", "disaster-relief", "escrow", "usdc"]
categories = ["wasm", "cryptography::cryptocurrencies"]
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "22.0.0"

[dev-dependencies]
soroban-sdk = { version = "22.0.0", features = ["testutils"] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true